version: "3.8"

services:
  server:
    build: ./server
    env_file:
      - .env
    ports:
      - 5001:5001

  postgres:
    image: postgres:latest
    env_file:
      - .env
    volumes:
      - postgres-card-table:/var/lib/postgresql/data

  peerjs:
    image: peerjs/peerjs-server
    ports:
      - 9000:9000

volumes:
  postgres-card-table:
